services:
  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: backend
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    container_name: frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: blabla_note
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: blabla_note_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
