services:
  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api/.env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    container_name: frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: blabla_note
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
