CREATE TYPE "NoteStatus" AS ENUM ('UPLOADED', 'TRANSCRIBING', 'SUMMARIZING', 'READY', 'FAILED');

ALTER TABLE "Note"
ADD COLUMN "status" "NoteStatus" NOT NULL DEFAULT 'UPLOADED',
ADD COLUMN "errorMessage" TEXT,
ADD COLUMN "transcriptText" TEXT;
