name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npx playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build

  docker:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          docker-compose build
          docker tag backend ghcr.io/${{ github.repository_owner }}/backend:latest
          docker tag frontend ghcr.io/${{ github.repository_owner }}/frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
